# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kge_cpp <- function(obs, sim, na_rm = TRUE) {
    .Call(`_tidyhydro_kge_cpp`, obs, sim, na_rm)
}

mse_cpp <- function(truth, estimate, na_rm = TRUE) {
    .Call(`_tidyhydro_mse_cpp`, truth, estimate, na_rm)
}

nse_cpp <- function(truth, estimate, performance = FALSE, na_rm = TRUE) {
    .Call(`_tidyhydro_nse_cpp`, truth, estimate, performance, na_rm)
}

pbias_cpp <- function(truth, estimate, performance = FALSE, na_rm = TRUE) {
    .Call(`_tidyhydro_pbias_cpp`, truth, estimate, performance, na_rm)
}

press_cpp <- function(truth, estimate, na_rm = TRUE) {
    .Call(`_tidyhydro_press_cpp`, truth, estimate, na_rm)
}

sfe_cpp <- function(truth, estimate, na_rm = TRUE) {
    .Call(`_tidyhydro_sfe_cpp`, truth, estimate, na_rm)
}

