# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nse_cpp <- function(truth, estimate, performance = FALSE, na_rm = TRUE) {
    .Call(`_tidyhydro_nse_cpp`, truth, estimate, performance, na_rm)
}

pbias_cpp <- function(truth, estimate, performance = FALSE, na_rm = TRUE) {
    .Call(`_tidyhydro_pbias_cpp`, truth, estimate, performance, na_rm)
}

press_cpp <- function(truth, estimate, na_rm = TRUE) {
    .Call(`_tidyhydro_press_cpp`, truth, estimate, na_rm)
}

